name: cdev
options:
  bundleIdPrefix: com.brianly
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

targets:
  cdev:
    type: application
    platform: iOS
    sources:
      - path: cdev
        excludes:
          - "**/*.xcassets/*/Contents.json"
    resources:
      - path: cdev/Resources/Assets.xcassets
      - path: cdev/Info.plist
    info:
      path: cdev/Info.plist
      properties:
        CFBundleDisplayName: cdev
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Camera access is needed to scan QR codes for connecting to cdev-agent"
        NSLocalNetworkUsageDescription: "Local network access is needed to connect to cdev-agent on your computer"
        NSBonjourServices:
          - "_http._tcp"
          - "_https._tcp"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        INFOPLIST_FILE: cdev/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.brianly.cdev
        CODE_SIGN_STYLE: Automatic

  cdevTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: cdevTests
    dependencies:
      - target: cdev
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brianly.cdevTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/cdev.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/cdev"
        BUNDLE_LOADER: "$(TEST_HOST)"

  cdevUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: cdevUITests
    dependencies:
      - target: cdev
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brianly.cdevUITests
        TEST_TARGET_NAME: cdev

schemes:
  cdev:
    build:
      targets:
        cdev: all
        cdevTests: [test]
        cdevUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - cdevTests
        - cdevUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
